version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./saved_models:/app/saved_models
      - .:/app
    environment:
      - DATABASE_URL=sqlite:////app/sqli_logs.db

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
